### ISSUE TITLE
Tasks from other drivers are still visible when you log in

### ISSUE THREAD

**Issue by GuidoHaagen** [coopcycle/coopcycle-app#415]
When you log into Coopcycle the list is not automatically refreshed and you can see stops from the driver who was logged in previously. That is causing confusion. 

Once you reload you see the right stops

**Comment by alexsegura** [comment]
This is "normal" because tasks are persisted to allow functioning offline. 

What we should do is clear storage upon logout.

**Comment by ERAMANrepartos** [comment]
Have we done clear storage upon logout? @alexsegura

**Comment by GuidoHaagen** [comment]
To me kind of related: @ERAMANrepartos 
- we are still suffering from beeing logged out during our tour. It takes a lot of time. Maybe clearing cach after log out would help

**Comment by alexsegura** [comment]
Original issue should have been fixed in 41978fa40bb9b25b2e0e26fe5523d2cb42e3bb9b

**Comment by ERAMANrepartos** [comment]
@GuidoHaagen 
This is still occurring? The original issue i mean. If not, could we make a new issue for the other thing you have mentioned?

**Comment by GuidoHaagen** [comment]
Hello @Paul-Eraman-CoopCycle 

I dont think so. Can be closed. 

The other thing is still happening. I will create an other issue.

**Comment by GuidoHaagen** [comment]
The other bug is this one: 
https://github.com/coopcycle/coopcycle-app/issues/1236
